INSERT INTO EmployeeTypes(Name) VALUES ('Receptionist')

INSERT INTO Employees(EmployeeTypeID, FirstName, LastName, Gender, BirthDate, PhoneNumber, Email, Address)
VALUES (1, 'Ha', 'Phi Hung', 'MALE', '2002-05-05', '0123456789', 'hung55@gmail.com', 'abcde'),
(1, 'Nguyen', 'Nhan Vien', 'FEMALE', '2000-01-01', '0987654321', 'Vỉen123@gmail.com', 'daljdls')

INSERT INTO Countries(Name) VALUES
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Angola'),
('Antigua & Deps'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bolivia'),
('Bosnia Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina'),
('Burundi'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Cape Verde'),
('Central African Rep'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Congo'),
('Congo {Democratic Rep}'),
('Costa Rica'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('East Timor'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Greece'),
('Grenada'),
('Guatemala'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland {Republic}'),
('Israel'),
('Italy'),
('Ivory Coast'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Korea North'),
('Korea South'),
('Kosovo'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Myanmar, {Burma}'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russian Federation'),
('Rwanda'),
('St Kitts & Nevis'),
('St Lucia'),
('Saint Vincent & the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome & Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Swaziland'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Togo'),
('Tonga'),
('Trinidad & Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Vatican City'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe')

INSERT INTO Customers(FirstName, LastName, IdNumberType, IdNumber, Gender, 
PhoneNumber, Address, City, Province, CountryId, PaymentMethod, CardNumber, ExpireDate)
VALUES 
('Ha', 'Van Nam', 'CMND', '0123456789', 'MALE', 
'0123456789', 'abcde', 'Nha Trang', 'Khanh Hoa', 193, 'CASH', null, null),
('John', 'Xina', 'PASSPORT', '123456789', 'MALE',
'+112 382480532', 'abcde',  'Lincoln', 'Nebraska', 187, 'VISA', '1234', '2030-01-01')

INSERT INTO RoomTypes(Name, Description, NumberOfPeople, FullDayRate, HalfDayRate)
VALUES
('Deluxe', 'Has window, banquet, flat-screen TV', 4, 1000000, 500000),
('Standard', null, 2, 300000, 150000)

INSERT INTO Rooms(RoomNumber, RoomTypeId, [Floor], Status)
VALUES (100, 2, 1, 'IN_USE'), (101, 2, 1, 'EMPTY'), (102, 2, 1, 'IN_WORK'),
(200, 1, 2, 'EMPTY'), (201, 1, 2, 'IN_USE'), (202, 1, 2, 'EMPTY')

INSERT INTO Reservations(ArrivalTime, DepartureTime, RoomId, CustomerId, EmployeeID, [Status])
VALUES ('2022-05-11', '2022-05-13', 4, 2, 1, 'RESERVED'),
('2022-05-09', '2022-05-14', 2, 3, 2, 'CHECKED_IN')

SELECT ArrivalTime, DepartureTime, Rooms.RoomNumber, 
Customers.FirstName, Customers.LastName, [Reservations].[Status]
FROM Reservations, Customers, Rooms
WHERE Reservations.CustomerId = Customers.CustomerId
AND Reservations.RoomId = Rooms.RoomId
